name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Clone and checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Install dependencies
      run: dotnet workload install aspire

    - name: Build
      run: |
        dotnet restore --configfile NuGet.config
        dotnet build --tl -c Release
