name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Clone and checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Install .NET MAUI workload
      run: |
        dotnet workload install maui

    - name: Build
      run: |
        dotnet restore --configfile NuGet.config
        dotnet build -c Release
